on: [ push, workflow_dispatch ]

env:
  IMAGE_NAME: ${{ github.repository }}:${{ github.sha }}
  
permissions:
    id-token: write
    contents: write             
    security-events: write  
    
jobs:
  build-and-scan:
    name: Build and scan image
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Build the image
        run: docker build -t $IMAGE_NAME .
        
      - name: init codeql
        uses: github/codeql-action/init@v2
        if: always()

      - name: Prisma Cloud image scans
        id: scan
        uses: PaloAltoNetworks/prisma-cloud-scan@v1
        if: always()
      
        with:
          pcc_console_url: ${{ secrets.PCC_CONSOLE_URL }}
          pcc_user: ${{ secrets.PCC_USER }}
          pcc_pass: ${{ secrets.PCC_PASS }}
          image_name: ${{ env.IMAGE_NAME }}
          
      - name: Convert JSON to SARIF
        run: |
          # Install the required dependencies
           npm install -g json-to-sarif  

          # Convert the JSON file to SARIF
          json-to-sarif --input pcc_scan_results.json --output pcc_scan_results.sarif
        if: always()
          
     
      # (Optional) for compatibility with GitHub's code scanning alerts
      - name: Upload SARIF file
        if: ${{ always() }} # necessary if using failure thresholds in the image scan
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: pcc_scan_results.sarif
