on: [ push, workflow_dispatch ]

env:
  IMAGE_NAME: ${{ github.repository }}:${{ github.sha }}
  
permissions:
    id-token: write
    contents: write             
    security-events: write  
    
jobs:
  build-and-scan:
    name: Build and scan image
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Build the image
        run: docker build -t $IMAGE_NAME .
        
     # - name: init codeql
      #  uses: github/codeql-action/init@v2
      #  if: always()

      - name: Prisma Cloud image scans
        id: scan
        uses: PaloAltoNetworks/prisma-cloud-scan@v1
        if: always()
      
        with:
          pcc_console_url: ${{ secrets.PCC_CONSOLE_URL }}
          pcc_user: ${{ secrets.PCC_USER }}
          pcc_pass: ${{ secrets.PCC_PASS }}
          image_name: ${{ env.IMAGE_NAME }}
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
        if: always()
      - name: Run Python script
        run: python parser.py  ${{ steps.scan.outputs.sarif_file }} >> ${{ steps.scan.outputs.sarif_file }}
        if: always()
 
     #In this example, the GitHub Actions 
      - name: Upload SARIF reports to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
         sarif_file: ${{ steps.scan.outputs.sarif_file }}
     
       
       
       
       
       
       
       
       
