name: Terraform Security Scan

on:
  push:
    branches:
      - main
      # Add other branches if needed

jobs:
  tfsec:
    name: Tfsec Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Tfsec
        run: |
          curl -L -o tfsec https://github.com/tfsec/tfsec/releases/latest/download/tfsec-linux-amd64
          chmod +x tfsec
          sudo mv tfsec /usr/local/bin/

      - name: Run Tfsec and Generate SARIF Output
        id: tfsec
        run: |
          tfsec --format=sarif ./ > results.sarif

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
